### PR TITLE
Discussion on advanced indexing and natural contraction

### PR DESCRIPTION
**Pull request by ctongfei**
Added discussions on broadcasting and advanced indexing (co-developed with Chu-Cheng Lin @kitsing (https://kitsing.github.io) and me on a JHU CLSP whiteboard) in Ch. 5,
and natural tensor contraction in Ch. 6.3.

Feedback is welcome!

### CODE REVIEW

**Comment by davidweichiang** [comment]
Thanks! If I understand correctly, there are two main proposals here:

1. Indexing a tensor by another tensor (of integers)

Personally I've always found this to be one of the more complex aspects of NumPy/PyTorch. Some people are giving us feedback that even broadcasting makes too much happen behind-the-scenes for math notation. Is there a strong use case for this in papers?

Also, I have a technical question: since the indexee has named (unordered) indices, shouldn't advIdx's second argument be a named (unordered) tuple?

2. A contraction operator that contracts all pairs of indices with the same name

We discussed the possibility of an operator that contracts all pairs of indices (i*, i), and thought that it would be preferable to have the contracted indices written out. I think in most cases, there aren't going to be that many indices, so the burden of writing them out is not high.

**Comment by ctongfei** [comment]
Thanks @davidweichiang !

 >  Personally I've always found this to be one of the more complex aspects of NumPy/PyTorch. Some people are giving us feedback that even broadcasting makes too much happen behind-the-scenes for math notation. Is there a strong use case for this in papers?

I agree that these might be too implicit for the sake of math notations. However, since these operations do happen a lot, and advanced indexing is pretty hard to understand, I believe that such a formal treatment of it would be extremely helpful (It certainly did help me a lot writing code involving these advanced indexing). 

> Also, I have a technical question: since the indexee has named (unordered) indices, shouldn't advIdx's second argument be a named (unordered) tuple?

Thanks. When @kitsing and I were discussing this, we operated under the assumption that axes are named and ordered, instead of unordered like this proposal. I'll update this to a record-based notation.

 > We discussed the possibility of an operator that contracts all pairs of indices (i*, i), and thought that it would be preferable to have the contracted indices written out. I think in most cases, there aren't going to be that many indices, so the burden of writing them out is not high.

I believe that introducing such an operator is useful for various sum/product algorithms so that different *shapes* can be abstracted away, like the BP example I listed.

**Comment by davidweichiang** [comment]
Formalizing advanced indexing would be interesting, but if the purpose isn't to recommend it for math notation, it should go in separate document from this one. At any rate, would it be simpler to define it first for the one-indexer case as:



Then for the two-indexer case:



and then generalize to any number of indexers?

**Comment by ctongfei** [comment]
Yeah that is the gist of the proposal on advanced indexing.

**Comment by ctongfei** [comment]
Updated with named tuple notations for advanced indexing

**Comment by davidweichiang** [comment]
I incorporated your material on advanced indexing into a possible new section on extensions (#19).

The natural contraction operator I think can be simulated using the existing contraction operator (just put a subscript dom(S), dom(T) where S and T are the shapes of the operands). But I wonder if the BP example could be combined with the existing example on Bayes' rule to form an extended example on using named indices for discrete random variables? @srush?

**Comment by srush** [comment]
Yeah, I like the idea of having a prob BP section. In fact Factor Graphs basically map one-to-one with named contractions. 

I'm going to close this for now though and make an issue.

**Comment by ctongfei** [comment]
Thanks @davidweichiang and @srush ! Looking forward to future discussions.

**Pull request closed without merging**
