### PR TITLE
Alternatives

### LINKED ISSUE #32: Add a section on "why not X notation"...
where X is

- Einstein summation convention or einsum
- abstract index notation
- ...

### PR DESCRIPTION
**Pull request by davidweichiang**
Closes #32.

### CODE REVIEW

**Comment by srush** [comment]
This looks great.

**Comment by davidweichiang** [comment]
@srush do you have anything to add esp. for the “Code” section? It’s pretty brief.

**Comment by srush** [comment]
The code section may not be necessary. It is a bit of a strawman, as I haven't heard anyone propose that people use code in papers for this. We could discuss a bit more some of the choices that were made to avoid "memory layout" based elements in our notation.

**Comment by davidweichiang** [comment]
Ha, that’s true, mainly I just wanted this section to have more than one subsection!

**Comment by srush** [comment]
Well, maybe we will come up with others as we go.

**Pull request merged**
