### PR TITLE
Define tensor indexes without explicit size 

### PR DESCRIPTION
**Pull request by davidweichiang**
Trying out notation from #18 and @ekshaks that lets you define tensor sets and not have to repeat the size over and over.

### CODE REVIEW

**Comment by davidweichiang** [comment]
@srush what do you think about this? Especially

image

(@boazbk writes an "ax" above the equals, but I have not yet changed "named index set" to "axis".)

**Comment by srush** [comment]
I will read today. Getting my recs done :/

**Comment by boazbk** [comment]
@srush Please also take a look at discussion on https://github.com/namedtensor/notation/pull/18 and my short version https://github.com/boazbk/notation/blob/main/short.pdf

**Comment by srush** [comment]
Huh, so I don't totally know how we resolve the differences here. Maybe we can setup a phone call? 

My view: the two methods are very similar. My strong preference is for the user to only see names + broadcasting (and ideally renaming only in corner-cases). 

Boaz's method: I like having labels without explicit lengths, so that seems like a win. But I really don't need them to be types or sets, and I would rather not have any notation like A_i , which just seems confusing to me and clashes with unordered notation. 

David's method: I am not convinced about the =idx thing. Having free variable sizes seems fine to me, within the scope of a function they seem to be fully understandable?  Even in attention with seq, seq', what is the n adding. Nothing would fail without that.

**Comment by davidweichiang** [comment]
I'm totally open to alternatives to =ind. We had talked previously about writing |layer| = d_model, which works as long as we know that the indices of layer are integers.

I kept the [n] on seq because its length will be different from sentence to sentence.

**Comment by srush** [comment]
So I think my intuition is differing from the notation. I really want the names to be bound at the function level. 

> I kept the [n] on seq because its length will be different from sentence to sentence.

This is the part I'm confused about though. From the perspective of the function type, why does it matter if that changes? Isn't that handled by the caller? 

> We had talked previously about writing |layer| = d_model, which works as long as we know that the indices of layer are integers.

Maybe I don't understand why this is needed in examples. I could see maybe in an experimental section, or at top level declarations.

**Comment by davidweichiang** [comment]
> From the perspective of the function type, why does it matter if that changes? Isn't that handled by the caller?

I guess it just seems strange to me for a function to be defined on a set that contains tensors of different sizes. However, I don't think there would be much harm in dropping the [n]s. I can just go on thinking to myself that there's really a family of Att functions being defined, one for each sequence length.

> Maybe I don't understand why this is needed in examples. I could see maybe in an experimental section, or at top level declarations.

I think it's fine to drop it in many cases. Generally, I'm including it when the size needs to be used somewhere. In the case of d_model, the word embeddings are scaled \sqrt{d_model}. It would be better to write \sqrt{|layer|} but I haven't done that yet.

**Comment by boazbk** [comment]
> I think it's fine to drop it in many cases. Generally, I'm including it when the size needs to be used somewhere. In the case of d_model, the word embeddings are scaled \sqrt{d_model}. It would be better to write \sqrt{|layer|} but I haven't done that yet.

I think \sqrt{|layer|} is more informative than \sqrt{d_model}.  Can also use \sqrt{|layer(A)|} if there are several tensors with a layer axis with a different support.

It only makes sense to define a separate variable for  the length of this axis if we use it time and again.

**Comment by davidweichiang** [comment]
The last commit should look better, I hope. It would be nice to get rid of the last few \nsets (sudoku, conv, maxpool).

**Comment by davidweichiang** [comment]
We don’t yet distinguish between an index set and support. Still thinking about that one.

**Comment by davidweichiang** [comment]
@srush how does this look now?

**Comment by srush** [comment]
Love it. Merging in.

**Pull request merged**
